export const PRICING_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    description: 'Cho giáo viên cá nhân muốn thử nghiệm.',
    price: 0,
    priceLabel: 'Miễn phí',
    priceUnit: '',
    badge: null,
    popular: false,
    cta: 'Bắt đầu miễn phí',
    features: [
      { text: '1 lớp học, tối đa 30 học sinh', included: true },
      { text: 'Mascot AI cơ bản', included: true },
      { text: '50 quiz/tháng', included: true },
      { text: 'Dashboard phân tích cơ bản', included: true },
      { text: 'Phần cứng IoT', included: false },
      { text: 'API tích hợp LMS', included: false },
      { text: 'Hỗ trợ ưu tiên', included: false },
    ],
    accentColor: 'slate',
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'Cho giáo viên & tổ bộ môn chuyên nghiệp.',
    price: 299000,
    priceLabel: '299.000₫',
    priceUnit: '/tháng',
    badge: 'Phổ biến nhất',
    popular: true,
    cta: 'Dùng thử 30 ngày',
    features: [
      { text: 'Không giới hạn lớp & học sinh', included: true },
      { text: 'Mascot AI nâng cao + tùy chỉnh', included: true },
      { text: 'Quiz & mini-game không giới hạn', included: true },
      { text: 'Dashboard chi tiết + xuất báo cáo', included: true },
      { text: 'Content Studio đầy đủ', included: true },
      { text: 'API tích hợp LMS', included: true },
      { text: 'Hỗ trợ ưu tiên 24/7', included: true },
    ],
    accentColor: 'sky',
  },
  {
    id: 'school',
    name: 'School + Hardware',
    description: 'Giải pháp toàn diện cho nhà trường.',
    price: null,
    priceLabel: 'Liên hệ',
    priceUnit: '',
    badge: 'Enterprise',
    popular: false,
    cta: 'Đặt lịch tư vấn',
    features: [
      { text: 'Tất cả tính năng Pro', included: true },
      { text: 'Bộ phần cứng IoT cho mỗi lớp', included: true },
      { text: 'Lắp đặt & đào tạo tại chỗ', included: true },
      { text: 'Quản lý đa trường (multi-campus)', included: true },
      { text: 'SLA 99.9% uptime', included: true },
      { text: 'Account manager chuyên trách', included: true },
      { text: 'Tùy chỉnh mascot theo thương hiệu trường', included: true },
    ],
    accentColor: 'violet',
    trustBox: {
      title: 'Cam kết minh bạch về phần cứng',
      items: [
        'Phần cứng thuê bao — không mua đứt. Trả theo tháng, hủy bất kỳ lúc nào.',
        'Bảo hành 24 tháng, đổi mới nếu lỗi kỹ thuật.',
        'Hỗ trợ cập nhật firmware OTA tự động — luôn phiên bản mới nhất.',
        'Fair Use Policy: 500 thiết bị/trường. Liên hệ để mở rộng.',
      ],
    },
  },
];

export const PRICING_FAQ = [
  {
    question: 'Tôi có thể hủy bất kỳ lúc nào không?',
    answer: 'Có. Tất cả gói đều không ràng buộc hợp đồng dài hạn. Bạn có thể hủy hoặc downgrade bất cứ lúc nào.',
  },
  {
    question: 'Phần cứng IoT hoạt động như thế nào?',
    answer: 'Thiết bị plug-and-play, kết nối Bluetooth với hub trung tâm. Không cần wifi riêng cho từng thiết bị. Giáo viên tự lắp trong 10 phút.',
  },
  {
    question: 'Có hỗ trợ tích hợp LMS hiện tại không?',
    answer: 'Gói Pro trở lên hỗ trợ API tích hợp với Moodle, Google Classroom, Microsoft Teams for Education.',
  },
];
