export const PRICING_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    description: 'Cho giáo viên cá nhân muốn thử nghiệm.',
    price: 0,
    priceLabel: 'Miễn phí',
    priceUnit: '',
    badge: null,
    popular: false,
    cta: 'Bắt đầu miễn phí',
    features: [
      { text: '1 lớp học, tối đa 30 học sinh', included: true },
      { text: 'Người bạn học tập thông minh cơ bản', included: true },
      { text: '50 bộ câu hỏi mỗi tháng', included: true },
      { text: 'Bảng theo dõi lớp học cơ bản', included: true },
      { text: 'Thiết bị lớp học', included: false },
      { text: 'Kết nối với hệ thống học tập của trường', included: false },
      { text: 'Hỗ trợ ưu tiên', included: false },
    ],
    accentColor: 'slate',
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'Cho giáo viên & tổ bộ môn chuyên nghiệp.',
    price: 119000,
    priceLabel: '119.000₫',
    priceUnit: '/tháng',
    badge: 'Phổ biến nhất',
    popular: true,
    cta: 'Dùng thử 14 ngày',
    features: [
      { text: 'Không giới hạn lớp & học sinh', included: true },
      { text: 'Người bạn học tập thông minh nâng cao', included: true },
      { text: 'Bộ câu hỏi và trò chơi ngắn không giới hạn', included: true },
      { text: 'Bảng theo dõi chi tiết + xuất báo cáo', included: true },
      { text: 'Không gian soạn nội dung đầy đủ', included: true },
      { text: 'Kết nối với hệ thống học tập của trường', included: true },
      { text: 'Hỗ trợ ưu tiên 24/7', included: true },
    ],
    accentColor: 'sky',
  },
  {
    id: 'school',
    name: 'Nhà trường + Thiết bị',
    description: 'Giải pháp toàn diện cho nhà trường.',
    price: null,
    priceLabel: 'Liên hệ',
    priceUnit: '',
    badge: 'Cho nhà trường',
    popular: false,
    cta: 'Đặt lịch tư vấn',
    features: [
      { text: 'Tất cả tính năng Pro', included: true },
      { text: 'Bộ thiết bị lớp học cho mỗi phòng', included: true },
      { text: 'Lắp đặt & đào tạo tại chỗ', included: true },
      { text: 'Quản lý nhiều cơ sở trong cùng một hệ thống', included: true },
      { text: 'Cam kết vận hành ổn định 99.9%', included: true },
      { text: 'Chuyên viên đồng hành riêng', included: true },
      { text: 'Tùy chỉnh nhân vật theo thương hiệu trường', included: true },
    ],
    accentColor: 'violet',
    trustBox: {
      title: 'Cam kết minh bạch về phần cứng',
      items: [
        'Phần cứng thuê bao — không mua đứt. Trả theo tháng, hủy bất kỳ lúc nào.',
        'Bảo hành 24 tháng, đổi mới nếu lỗi kỹ thuật.',
        'Hỗ trợ cập nhật thiết bị tự động — luôn dùng phiên bản mới nhất.',
        'Mỗi trường dùng tối đa 500 thiết bị trong gói tiêu chuẩn. Liên hệ để mở rộng.',
      ],
    },
  },
];
