export const PRICING_PLANS = [
  {
    id: 'free',
    name: 'Free',
    eyebrow: 'Dùng thử nhẹ nhàng',
    description: 'Cho giáo viên bắt đầu tổ chức lớp học đầu tiên trên Mascoteach.',
    monthlyPriceLabel: '0đ',
    yearlyPriceLabel: '0đ',
    monthlyUnit: '/ tháng',
    yearlyUnit: '/ năm',
    cta: 'Bắt đầu miễn phí',
    href: '/register',
    tone: 'free',
    features: [
      'Tối đa 30 học sinh',
      '5 bộ câu hỏi mỗi tháng',
      'Bảng theo dõi lớp học cơ bản',
      'Hỗ trợ qua email',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    eyebrow: 'Phù hợp nhất',
    description: 'Cho giáo viên cần soạn bài tập, tạo trò chơi và theo dõi lớp học thường xuyên.',
    monthlyPriceLabel: '119.000đ',
    yearlyPriceLabel: '99.000đ',
    monthlyUnit: '/ tháng',
    yearlyUnit: '/ tháng',
    monthlyBillingNote: 'Thanh toán 119.000đ/30 ngày',
    yearlyBillingNote: 'Thanh toán 1.188.000đ/365 ngày',
    cta: 'Nâng cấp lên Pro',
    href: '/pricing',
    tone: 'pro',
    featured: true,
    features: [
      'Không giới hạn học sinh',
      'Bộ câu hỏi và trò chơi ngắn không giới hạn',
      'Bảng theo dõi chi tiết và xuất báo cáo',
      'Ưu tiên hỗ trợ và cập nhật sớm',
    ],
  },
];
